# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
 - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
   displayName: 'Use Terraform latest'
   inputs:
     terraformVersion: $(terraform_version)
